"""Constants used across evidence reducers."""

from __future__ import annotations

import re

MIN_COMPARISON_HINTS = (
    "least",
    "fewest",
    "lowest",
    "minimum",
    "smallest",
    "earliest",
    "shortest",
)
MAX_COMPARISON_HINTS = (
    "most",
    "highest",
    "maximum",
    "largest",
    "greatest",
    "latest",
    "longest",
)
NUMERIC_QUESTION_HINTS = (
    "how many",
    "what number",
    "what is the number",
    "what was the number",
    "what is the highest number",
    "what was the highest number",
    "what is the maximum number",
    "what was the maximum number",
    "what is the least number",
    "what was the least number",
    "what is the minimum number",
    "what was the minimum number",
)
LABEL_COLUMN_HINTS = (
    "country",
    "nation",
    "noc",
    "committee",
    "team",
    "name",
    "city",
    "state",
    "player",
    "athlete",
    "school",
    "club",
    "title",
)
GENERIC_NUMERIC_HEADERS = {
    "rank",
    "place",
    "pos",
    "position",
    "year",
    "no",
    "no.",
    "#",
}
STOP_WORDS = {
    "the",
    "and",
    "with",
    "from",
    "that",
    "this",
    "what",
    "which",
    "give",
    "your",
    "answer",
    "there",
    "their",
    "have",
    "had",
    "into",
    "than",
    "then",
    "for",
    "was",
    "were",
    "are",
    "who",
    "whom",
    "whose",
    "when",
    "where",
    "least",
    "most",
    "highest",
    "lowest",
    "maximum",
    "minimum",
    "smallest",
    "largest",
    "first",
    "last",
    "alphabetical",
    "order",
    "return",
}
NUMBER_RE = re.compile(r"-?\d+(?:,\d{3})*(?:\.\d+)?")
YEAR_RE = re.compile(r"\b(1[0-9]{3}|20[0-9]{2})\b")
PARENTHETICAL_ROW_RE = re.compile(
    r"^(?P<label>[^()]+?)\s*\((?P<number>-?\d+(?:,\d{3})*(?:\.\d+)?)\)\s*$"
)
NASA_AWARD_RE = re.compile(
    r"(?:nasa\s+award\s+(?:number|no\.?)|award\s+(?:number|no\.?)|supported by[^.\n]{0,100}?)\s*[:#]?\s*([A-Z0-9-]{8,})",
    flags=re.IGNORECASE,
)
PERSON_NAME_RE = r"[A-Z][A-Za-z''.\-]+(?:\s+[A-Z][A-Za-z''.\-]+){0,3}"
ROSTER_NUMBERED_NAME_RE = re.compile(
    rf"^(?P<number>\d{{1,3}})\s+(?P<name>{PERSON_NAME_RE})$"
)
EXTINCT_COUNTRY_NAMES = {
    "east germany",
    "german democratic republic",
    "west germany",
    "yugoslavia",
    "soviet union",
    "ussr",
    "czechoslovakia",
    "rhodesia",
    "serbia and montenegro",
}
TEXT_SPAN_ATTRIBUTE_HINTS = (
    "surname",
    "last name",
    "first name",
    "city name",
)
METRIC_TOKEN_ALIASES = {
    "at bats": {"ab"},
    "walks": {"bb"},
    "bases on balls": {"bb"},
    "runs batted in": {"rbi"},
    "home runs": {"hr"},
    "wins": {"w"},
    "losses": {"l"},
}
IOC_COUNTRY_CODES = {
    "argentina": "ARG",
    "armenia": "ARM",
    "australia": "AUS",
    "austria": "AUT",
    "azerbaijan": "AZE",
    "bahamas": "BAH",
    "bahrain": "BRN",
    "barbados": "BAR",
    "belarus": "BLR",
    "belgium": "BEL",
    "bermuda": "BER",
    "bolivia": "BOL",
    "bosnia and herzegovina": "BIH",
    "botswana": "BOT",
    "brazil": "BRA",
    "bulgaria": "BUL",
    "cambodia": "CAM",
    "cameroon": "CMR",
    "canada": "CAN",
    "chile": "CHI",
    "china": "CHN",
    "chinese taipei": "TPE",
    "colombia": "COL",
    "costa rica": "CRC",
    "croatia": "CRO",
    "cuba": "CUB",
    "cyprus": "CYP",
    "czech republic": "CZE",
    "czechia": "CZE",
    "denmark": "DEN",
    "dominican republic": "DOM",
    "ecuador": "ECU",
    "egypt": "EGY",
    "estonia": "EST",
    "ethiopia": "ETH",
    "finland": "FIN",
    "france": "FRA",
    "georgia": "GEO",
    "germany": "GER",
    "ghana": "GHA",
    "great britain": "GBR",
    "greece": "GRE",
    "guatemala": "GUA",
    "haiti": "HAI",
    "hong kong": "HKG",
    "hungary": "HUN",
    "iceland": "ISL",
    "india": "IND",
    "indonesia": "INA",
    "iran": "IRI",
    "iraq": "IRQ",
    "ireland": "IRL",
    "israel": "ISR",
    "italy": "ITA",
    "ivory coast": "CIV",
    "jamaica": "JAM",
    "japan": "JPN",
    "kazakhstan": "KAZ",
    "kenya": "KEN",
    "kosovo": "KOS",
    "kyrgyzstan": "KGZ",
    "latvia": "LAT",
    "lebanon": "LBN",
    "lithuania": "LTU",
    "luxembourg": "LUX",
    "malaysia": "MAS",
    "mexico": "MEX",
    "moldova": "MDA",
    "mongolia": "MGL",
    "montenegro": "MNE",
    "morocco": "MAR",
    "namibia": "NAM",
    "netherlands": "NED",
    "new zealand": "NZL",
    "nigeria": "NGR",
    "north korea": "PRK",
    "north macedonia": "MKD",
    "norway": "NOR",
    "pakistan": "PAK",
    "panama": "PAN",
    "paraguay": "PAR",
    "peru": "PER",
    "philippines": "PHI",
    "poland": "POL",
    "portugal": "POR",
    "puerto rico": "PUR",
    "qatar": "QAT",
    "romania": "ROU",
    "russia": "RUS",
    "saint lucia": "LCA",
    "saudi arabia": "KSA",
    "serbia": "SRB",
    "singapore": "SGP",
    "slovakia": "SVK",
    "slovenia": "SLO",
    "south africa": "RSA",
    "south korea": "KOR",
    "soviet union": "URS",
    "spain": "ESP",
    "sweden": "SWE",
    "switzerland": "SUI",
    "syria": "SYR",
    "tajikistan": "TJK",
    "thailand": "THA",
    "trinidad and tobago": "TTO",
    "tunisia": "TUN",
    "turkey": "TUR",
    "ukraine": "UKR",
    "united arab emirates": "UAE",
    "united kingdom": "GBR",
    "united states": "USA",
    "united states of america": "USA",
    "uruguay": "URU",
    "uzbekistan": "UZB",
    "venezuela": "VEN",
    "vietnam": "VIE",
}
